<?php

namespace Hanafalah\KlinikStarterpack\Database\Seeders;

use Hanafalah\LaravelSupport\Concerns\Support\HasRequestData;
use Illuminate\Database\Seeder;

class SampleSeeder extends Seeder{
    use HasRequestData;

    protected $datas = [
        [
            'name' => 'Darah Vena',
            'flag' => 'Sample',
            'label' => 'BLOOD_VENOUS',
            'loinc_code' => 'LP15424-4',
            'collection_method' => 'Venipuncture',
            'specimen_type' => 'Whole Blood',
            'appearance' => 'Cairan merah',
            'container' => 'Tabung EDTA',
            'preservative' => 'EDTA',
            'volume_min_ml' => 3,
            'storage_condition' => '2–8°C',
            'transport_condition' => 'Segera suhu dingin',
            'transport_media' => null,
            'transport_time_limit' => '6 jam',
            'validity_period' => '6 jam',
            'priority' => 'Normal',
            'fasting_required' => true,
            'hazardous' => false,
            'biohazard_level' => 'Low',
            'aliquot_allowed' => true,
            'barcode_prefix' => 'VEN',
            'notes' => 'Puasa 8 jam jika tes glukosa',
        ],
        [
            'name' => 'Darah Arteri',
            'flag' => 'Sample',
            'label' => 'BLOOD_ARTERIAL',
            'loinc_code' => 'LP20802-6',
            'collection_method' => 'Arterial puncture',
            'specimen_type' => 'Whole Blood',
            'appearance' => 'Cairan merah terang',
            'container' => 'Tabung Heparin',
            'preservative' => 'Heparin',
            'volume_min_ml' => 1,
            'storage_condition' => 'Segera dianalisa',
            'transport_condition' => 'STAT suhu dingin',
            'transport_media' => null,
            'transport_time_limit' => '15 menit',
            'validity_period' => '15 menit',
            'priority' => 'STAT',
            'fasting_required' => false,
            'hazardous' => false,
            'biohazard_level' => 'Low',
            'aliquot_allowed' => false,
            'barcode_prefix' => 'ART',
            'notes' => 'Untuk analisa gas darah',
        ],
        [
            'name' => 'Serum',
            'flag' => 'Sample',
            'label' => 'SERUM',
            'loinc_code' => 'LP31388-9',
            'collection_method' => 'Venipuncture',
            'specimen_type' => 'Serum',
            'appearance' => 'Cair bening kekuningan',
            'container' => 'Tabung SST',
            'preservative' => null,
            'volume_min_ml' => 3,
            'storage_condition' => '2–8°C',
            'transport_condition' => 'Suhu dingin',
            'transport_media' => null,
            'transport_time_limit' => '24 jam',
            'validity_period' => '24 jam',
            'priority' => 'Normal',
            'fasting_required' => true,
            'hazardous' => false,
            'biohazard_level' => 'Low',
            'aliquot_allowed' => true,
            'barcode_prefix' => 'SER',
            'notes' => 'Biarkan bekuan ±30 menit sebelum sentrifugasi',
        ],
        [
            'name' => 'Plasma',
            'flag' => 'Sample',
            'label' => 'PLASMA',
            'loinc_code' => 'LP31387-1',
            'collection_method' => 'Venipuncture',
            'specimen_type' => 'Plasma',
            'appearance' => 'Cair kekuningan',
            'container' => 'Tabung EDTA/Heparin',
            'preservative' => 'EDTA/Heparin',
            'volume_min_ml' => 3,
            'storage_condition' => '2–8°C',
            'transport_condition' => 'Suhu dingin',
            'transport_media' => null,
            'transport_time_limit' => '24 jam',
            'validity_period' => '24 jam',
            'priority' => 'Normal',
            'fasting_required' => false,
            'hazardous' => false,
            'biohazard_level' => 'Low',
            'aliquot_allowed' => true,
            'barcode_prefix' => 'PLS',
            'notes' => 'Segera sentrifugasi',
        ],
        [
            'name' => 'Urin Pagi',
            'flag' => 'Sample',
            'label' => 'URINE_MORNING',
            'loinc_code' => 'LP29790-1',
            'collection_method' => 'Midstream clean-catch',
            'specimen_type' => 'Urine',
            'appearance' => 'Cairan kuning jernih',
            'container' => 'Pot steril',
            'preservative' => null,
            'volume_min_ml' => 10,
            'storage_condition' => 'Suhu ruang',
            'transport_condition' => 'Segera',
            'transport_media' => null,
            'transport_time_limit' => '2 jam',
            'validity_period' => '2 jam',
            'priority' => 'Normal',
            'fasting_required' => false,
            'hazardous' => false,
            'biohazard_level' => 'Low',
            'aliquot_allowed' => false,
            'barcode_prefix' => 'URN',
            'notes' => 'Urin pertama pagi hari',
        ],
        [
            'name' => 'Feses',
            'flag' => 'Sample',
            'label' => 'STOOL',
            'loinc_code' => 'LP29809-9',
            'collection_method' => 'Spontan',
            'specimen_type' => 'Stool',
            'appearance' => 'Padat/semi padat coklat',
            'container' => 'Pot steril',
            'preservative' => null,
            'volume_min_ml' => 5,
            'storage_condition' => 'Suhu ruang',
            'transport_condition' => 'Segera',
            'transport_media' => null,
            'transport_time_limit' => '2 jam',
            'validity_period' => '2 jam',
            'priority' => 'Normal',
            'fasting_required' => false,
            'hazardous' => true,
            'biohazard_level' => 'Low',
            'aliquot_allowed' => false,
            'barcode_prefix' => 'STL',
            'notes' => 'Hindari kontaminasi urine',
        ],
        [
            'name' => 'Sputum',
            'flag' => 'Sample',
            'label' => 'SPUTUM',
            'loinc_code' => 'LP29812-3',
            'collection_method' => 'Ekspektorasi',
            'specimen_type' => 'Sputum',
            'appearance' => 'Lendir kental keputihan',
            'container' => 'Pot steril',
            'preservative' => null,
            'volume_min_ml' => 2,
            'storage_condition' => '2–8°C',
            'transport_condition' => 'Segera',
            'transport_media' => null,
            'transport_time_limit' => '2 jam',
            'validity_period' => '2 jam',
            'priority' => 'Normal',
            'fasting_required' => false,
            'hazardous' => true,
            'biohazard_level' => 'Moderate',
            'aliquot_allowed' => false,
            'barcode_prefix' => 'SPT',
            'notes' => 'Ambil pagi sebelum makan',
        ],
        [
            'name' => 'Swab Nasofaring',
            'flag' => 'Sample',
            'label' => 'SWAB_NP',
            'loinc_code' => 'LP29618-5',
            'collection_method' => 'Swab stick',
            'specimen_type' => 'Swab',
            'appearance' => 'Swab stick dalam VTM',
            'container' => 'VTM (Viral Transport Medium)',
            'preservative' => null,
            'volume_min_ml' => null,
            'storage_condition' => '2–8°C',
            'transport_condition' => 'Segera',
            'transport_media' => 'VTM',
            'transport_time_limit' => '24 jam',
            'validity_period' => '24 jam',
            'priority' => 'Normal',
            'fasting_required' => false,
            'hazardous' => true,
            'biohazard_level' => 'Moderate',
            'aliquot_allowed' => false,
            'barcode_prefix' => 'NP',
            'notes' => 'Untuk PCR COVID-19',
        ],
        [
            'name' => 'Biopsi Jaringan',
            'flag' => 'Sample',
            'label' => 'BIOPSY',
            'loinc_code' => 'LP31755-9',
            'collection_method' => 'Eksisi/insisi',
            'specimen_type' => 'Tissue',
            'appearance' => 'Potongan jaringan',
            'container' => 'Pot formalin 10%',
            'preservative' => 'Formalin',
            'volume_min_ml' => null,
            'storage_condition' => 'Suhu ruang',
            'transport_condition' => 'Dalam fiksasi',
            'transport_media' => 'Formalin',
            'transport_time_limit' => 'Tidak terbatas',
            'validity_period' => 'Tak terbatas (dalam formalin)',
            'priority' => 'Normal',
            'fasting_required' => false,
            'hazardous' => true,
            'biohazard_level' => 'Moderate',
            'aliquot_allowed' => false,
            'barcode_prefix' => 'BIO',
            'notes' => 'Segera masukkan ke formalin',
        ],
    ];

    public function run()
    {
        foreach ($this->datas as $key => $data) {
            app(config('app.contracts.Sample'))->prepareStoreSample(
                $this->requestDTO(config('app.contracts.SampleData'), $data)
            );
        }

    }
}
